import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Image from "next/image";
import "./globals.css";

const raleway = Raleway({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <Image
          fill
          quality={100}
          objectFit="cover"
          className=".BackgroundImage position-absolute"
          src="/loginpage.png"
          alt="HomePage"
        />
        {children}
      </body>
    </html>
  );
}
