import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import Header  from "@/components/Header/index";
    
const raleway = Raleway({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: "300",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.variable} antialiased`}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
